// A QR code made today has to open tomorrow.
//
// A shared setup is a URL frozen into a picture: printed, pinned to a wall,
// photographed. Nothing can update it after the fact, so every change to the
// app is a change to how every code already out there is read. The failures
// are all silent — a node type renamed, a param key tidied, a default moved —
// and the app still opens, just with a different instrument than the one that
// was shared.
//
// fixtures/share-links.json holds links made by real past versions of the app,
// generated by that commit's own code. They are never regenerated: if one stops
// opening as what it was, the fix is a migration in src/presetformat.js, not a
// new fixture. When PRESET_VERSION is bumped, add a link made just before it.
//
// Run: npm run test:unit

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

globalThis.localStorage ??= {
  _m: new Map(),
  getItem(k) { return this._m.has(k) ? this._m.get(k) : null; },
  setItem(k, v) { this._m.set(k, String(v)); },
  removeItem(k) { this._m.delete(k); },
};

const { readShareUrl, decodeState, shareUrl, SHARE_BASE } = await import('../../src/share.js');
const { applyAll, snapshot } = await import('../../src/preset.js');
const { migrate, PRESET_VERSION } = await import('../../src/presetformat.js');

const FIXTURES = JSON.parse(readFileSync(new URL('fixtures/share-links.json', import.meta.url), 'utf8'));

// What every fixture was made with — see the generator in the commit that
// added this file: two params moved off their defaults and two cables, one
// with a curve and one inverted.
const WANT_MAPPINGS = [
  { audioParam: 'filter_freq', signal: 'hand_R_y', outMin: 200, outMax: 5000, curve: 'log', invert: false },
  { audioParam: 'lfo_depth', signal: 'pinch_L', outMin: 0, outMax: 0.5, curve: 'linear', invert: true },
];

for (const fx of FIXTURES) {
  test(`a link made by ${fx.made_by} still opens as what was shared (${fx.note})`, async () => {
    // The address first: it is the part a printed code can never change.
    assert.ok(fx.url.startsWith(SHARE_BASE), `the link points somewhere other than ${SHARE_BASE}`);
    const payload = readShareUrl(fx.url);
    assert.ok(payload, 'the fragment is still found');

    const data = await decodeState(payload);
    const { ok, newer } = applyAll(data);
    assert.ok(ok, 'recognised as a MotionMuse setup');
    assert.equal(newer, false, 'an old link is not mistaken for one from the future');
    assert.equal(data.label, 'fixture: right hand opens the filter');

    const now = snapshot();
    assert.equal(now.audio.params.filter_freq, 1234);
    assert.equal(now.audio.params.reverb_mix, 0.4);
    for (const want of WANT_MAPPINGS) {
      const got = now.mappings.find(m => m.audioParam === want.audioParam);
      assert.ok(got, `the cable into ${want.audioParam} survived`);
      for (const [k, v] of Object.entries(want)) assert.equal(got[k], v, `${want.audioParam}.${k}`);
    }
    // Whatever nodes it carried come back as the same types. A node type the
    // current app no longer knows is dropped by graph.load(), so a rename
    // without a migration fails exactly here.
    assert.deepEqual(now.graph.map(n => n.type), (data.graph ?? []).map(n => n.type));
  });
}

test('the oldest saves, before `v` was written, are upgraded rather than refused', () => {
  const old = { app: 'biosignal-sound', audio: { params: { osc_mix: 0.25 } } };
  const { data, newer } = migrate(old);
  assert.equal(data.v, PRESET_VERSION);
  assert.equal(newer, false);
  assert.equal(old.v, undefined, 'the input is left alone');

  assert.ok(applyAll(old).ok, 'the pre-rebrand tag still loads');
  // osc_mix was a 1↔2 crossfade; osc1 played at 1 - mix.
  assert.equal(snapshot().audio.params.osc1_volume, 0.75);
});

test('a setup from a newer app is applied, and says so', () => {
  const future = { ...snapshot(), v: PRESET_VERSION + 1, somethingNew: { x: 1 } };
  const { data, newer } = migrate(future);
  assert.equal(newer, true);
  assert.equal(data.v, PRESET_VERSION + 1, 'not downgraded: nothing here knows how');
  const res = applyAll(future);
  assert.ok(res.ok, 'most of a newer setup is still worth having');
  assert.equal(res.newer, true, 'and the caller is told, so it can tell the person');
});

// ── Where a code points ──────────────────────────────────────────────────

test('a code made on any deployment points at the one that is kept alive', () => {
  for (const here of [
    'https://dentarthurdent42.github.io/MotionMuse/',
    'https://dentarthurdent42.github.io/MotionMuse/index.html?x=1#s=old',
    'https://deploy-preview-57--motionmuse.netlify.app/',
    'https://motionmuse.pages.dev/index.html',
  ]) assert.equal(shareUrl('dABC', here), `${SHARE_BASE}#s=dABC`, here);
});

test('a code made while developing points back at the build being tested', () => {
  assert.equal(shareUrl('dABC', 'http://127.0.0.1:8080/index.html'), 'http://127.0.0.1:8080/index.html#s=dABC');
  assert.equal(shareUrl('dABC', 'https://localhost:8443/?dev=1#x'), 'https://localhost:8443/#s=dABC');
  assert.equal(shareUrl('dABC', 'https://192.168.1.20:8443/'), 'https://192.168.1.20:8443/#s=dABC');
});
